### ISSUE TITLE
Link in readme doesn't work 

### ISSUE THREAD

**Issue by Haroenv** [gaoxiaosong1113/vue-music#1]
It gives me a GitHub 404 page :smile:

**Comment by xiaoosnggao** [comment]
What?

**Comment by gaoxiaosong1113** [comment]
@Haroenv 说中文好嘛~~~  真心看不懂英文

**Comment by xiaoosnggao** [comment]
@Haroenv  I'm sorry, I'm not very familiar with English, can only rely on translation software

Wish to have a preview, direct access to the [http://www.gxspp.com/web/vue-music/#/recommended](http://www.gxspp.com/web/vue-music/#/recommended) this link,

**Comment by Haroenv** [comment]
Don't be sorry, it was just a very small typing mistake. I wish I could understand Chinese

Haroen Viaene

Sent from my phone
I

**Comment by xiaoosnggao** [comment]
@Haroenv 😄

**Comment by Haroenv** [comment]
You fixed it in the current readme ❤️
